/**
 * lib/copy.ts — 全部使用者可見文案（單一來源）。
 * 慣例：元件不得內嵌中文字串；語言紅線測試掃本檔（copy.test.ts），
 * 最終任務再全 repo grep 雙保險。
 * 文案原則：非託管講清楚；不出現 固定收益/保證/存款/代操。
 */
export const COPY = {
  common: {
    appName: "FILET",
    next: "下一步",
    retry: "重試",
    loading: "載入中…",
    notLoggedIn: "尚未登入——請先回到登入頁連接錢包。",
    backToLogin: "回登入頁",
    logout: "登出",
    nonCustodial: "Filet 永遠不會請你輸入私鑰或助記詞；所有簽署只會在你自己的錢包中完成。",
  },
  login: {
    subtitle: "資金留在你自己的錢包。策略照樣執行。",
    connect: "連接錢包",
    connecting: "連接中…",
    signingIn: "請在錢包中簽署登入訊息…",
    signInNote: "登入需要一筆免費的訊息簽名（不上鏈、不花費 gas）。",
    noWallet: "未偵測到瀏覽器錢包。請先安裝 MetaMask 後重新整理本頁。Filet 永遠不會請你輸入私鑰或助記詞。",
    rejected: "你在錢包中取消了簽署。準備好後再點一次「連接錢包」即可。",
    walletPanelTitle: "你的錢包",
    enginePanelTitle: "Filet 引擎",
    addrLabel: "地址",
    balanceLabel: "餘額",
    strategyLabel: "策略",
    strategyValue: "網格・多幣",
    engineStateLabel: "狀態",
    engineStateIdle: "待命",
    notConnected: "尚未連接",
    pillUnauthorized: "尚未授權",
    pillAuthorized: "trade-only・無提款權",
    footnote: "每筆成交收取 0.02%（2bp）builder fee，鏈上可驗。跟單有虧損風險，過往績效不代表未來結果。",
  },
  wizard: {
    stepNames: ["連接錢包", "風險確認", "簽署授權", "入金啟用"],
    step1Title: "錢包已連接",
    step2Title: "請確認以下事項",
    risk1: "我了解跟單有虧損風險",
    risk2: "我了解 Filet 僅持有下單權限，無法動用或提領我的資金",
    risk3: "我已閱讀費用說明（每筆成交 0.02%）",
    step3Title: "簽署兩筆授權",
    agentCardName: "ApproveAgent",
    agentCardDesc: "授權 Filet trade-only agent key 代下單，無提款權限。",
    feeCardName: "ApproveBuilderFee",
    feeCardDesc: "授權 builder fee 上限 0.1%，每筆成交依實際費率（0.02%）扣收。",
    signWithWallet: "以錢包簽署",
    stateUnsigned: "待簽署",
    stateAwaitingWallet: "請在錢包中確認…",
    stateSubmitting: "送出中…",
    stateSubmitted: "已送出，等待鏈上確認…",
    stateConfirmed: "已生效",
    stateRejected: "被拒絕",
    agentPreparing: "正在準備 agent 金鑰…",
    agentLabel: "agent 地址",
    reconnectTitle: "錢包未連接",
    reconnectHint: "你的登入仍有效，但瀏覽器錢包目前未連接（可能已上鎖）。請解鎖錢包並重新連接後繼續簽署；你的進度不會遺失。",
    reconnectButton: "重新連接錢包",
    step4Title: "入金檢查",
    // 「100 USDC」須與後端門檻同源：src/spark/config.py 的 MIN_BUILDER_BALANCE
    // （經 ApiConfig.min_user_deposit 生效於 /api/onboard/status 的 funded）。
    // 後端常數若改，這兩句文案要同步改——Task 14 review 檢查點。
    depositDetected: "已偵測到足額資金（≥ 100 USDC）",
    depositPending: "尚未偵測到足額資金（需 ≥ 100 USDC）。請將 USDC 轉入你自己的 Hyperliquid 帳戶（與登入錢包同一地址）；資金全程留在你的帳戶，Filet 無法動用或提領。",
    submitReview: "送出審核",
    submitted: "已送出審核。管理員核准後開始跟單；你隨時可回到本頁或績效頁查看狀態。",
    errors: {
      walletRejected: "簽署被拒絕——請在錢包中重試。Filet 永遠不會請你輸入私鑰或助記詞；簽署只會在你自己的錢包中完成。",
      signerMismatch: "簽名帳號與登入帳號不符——請在錢包中切回登入時使用的帳號後重試。這筆簽名不會被送出。",
      agentUnavailable: "金鑰服務暫時不可用，請稍後重試。",
      payloadFailed: "取得待簽內容失敗，請稍後重試。",
      hlTransient: "送出授權時網路不穩——可以放心重試，重複送出同一筆簽名不會造成重複授權。",
      hlSemantic: "Hyperliquid 拒絕了這筆授權。請點「重試」重新取得待簽內容再簽一次。",
      builderPaused: "系統暫停開通中，請聯絡我們再試。",
      verifyIncomplete: "尚有條件未完成（授權或資金未確認），請依畫面提示補齊後再送出。",
    },
  },
  perf: {
    title: "帳戶狀態",
    heroLabel: "跟單狀態",
    stateReady: "已就緒",
    stateInProgress: "開通進行中",
    walletPanelTitle: "你的錢包",
    enginePanelTitle: "Filet 引擎",
    addrLabel: "地址",
    fundedLabel: "資金門檻",
    fundedOk: "已達（≥ 100 USDC）",
    fundedNo: "未達（需 ≥ 100 USDC）",
    agentLabel: "agent",
    agentNone: "尚未生成",
    approvalsLabel: "授權",
    approvalsBoth: "兩筆皆已生效",
    approvalsPartial: "尚未完成",
    goOnboarding: "前往開通",
    feePanelTitle: "費用透明",
    feeRateNote: "費率 0.02%，逐筆鏈上可驗。",
    feeUpperNote: "你簽署的授權上限為 0.1%；實際僅收 0.02%。",
    refreshNote: "本頁每 30 秒自動更新。",
  },
  admin: {
    title: "待核准清單",
    empty: "目前沒有待核准的項目。",
    forbidden: "此頁僅限管理員。",
    note: "核准動作走人工 CLI（scripts/filet_activate.py），本頁唯讀。逐筆核對 builder_address。",
    cols: {
      account: "account_id",
      user: "user_address",
      agent: "agent_address",
      builder: "builder_address",
      network: "network",
      label: "label",
    },
  },
} as const;
